<?xml version="1.0" encoding="utf-8"?><Database Name="Chinook" Class="DataChinookDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NO142145;Initial Catalog=Chinook;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ChinookConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Album" Member="Albums">
    <Type Name="Album">
      <Column Name="AlbumId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="ArtistId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Artist_Album" Member="Artist" ThisKey="ArtistId" OtherKey="ArtistId" Type="Artist" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Artist" Member="Artists">
    <Type Name="Artist">
      <Column Name="ArtistId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Association Name="Artist_Album" Member="Albums" ThisKey="ArtistId" OtherKey="ArtistId" Type="Album" />
    </Type>
  </Table>
</Database>